namespace: logging

cadvisor:
  image: gcr.io/cadvisor/cadvisor:latest

grafana:
  image: grafana/grafana:10.4.1
  nodePort: 32000
  adminUser: admin
  adminPassword: admin
  tls:
    crt: ""
    key: ""
  storage:
    size: 5Gi
    nfsServer: X.X.X.X
    nfsPath: /export/grafana

loki:
  image: grafana/loki:2.9.0
  storage:
    size: 5Gi
    nfsServer: X.X.X.X
    nfsPath: /export/loki

prometheus:
  image: prom/prometheus:latest
  storage:
    size: 10Gi
    nfsServer: X.X.X.X
    nfsPath: /export/prometheus

scrapeTargets:
  kubelet:
    - ""
    - ""
    - ""
  kubeStateMetrics:
    - ""
    - ""
    - ""
