apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ .Values.namespace }}
data:
  grafana.ini: |
    [server]
    protocol = https
    cert_file = /etc/grafana/certs/tls.crt
    cert_key = /etc/grafana/certs/tls.key
    root_url = https://localhost:3000
    serve_from_sub_path = true

    [auth.anonymous]
    enabled = false
    org_role = Admin

    [users]
    default_theme = dark

