apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubelet-cadvisor'
        scheme: http
        static_configs:
          - targets:
          {{- range .Values.scrapeTargets.kubelet }}
            - "{{ . }}"
          {{- end }}
        metrics_path: /metrics/cadvisor
      - job_name: 'kubernetes-kube-state-metrics'
        static_configs:
          - targets:
          {{- range .Values.scrapeTargets.kubeStateMetrics }}
            - "{{ . }}"
          {{- end }}
